[rom]
title = "Benesta Dumper"
short-title = "Dumper"
category = "APPLET_TOOL"
default-locale = "en"
copyright = """\
Copyright (c) 2025 dogtopus
SPDX-License-Identifier: MIT\
"""
version = "1.0.1"

[metadata.en]
title = "Benesta Dumper"
short-title = "Dumper"
